/**
 * Mock TV series catalog for Viewesta — African cinema streaming.
 * TODO: Replace with API GET /series when backend is ready.
 */

export const mockSeries = [
  {
    id: 's1',
    title: 'Blood Sisters',
    year: 2022,
    rating: 7.0,
    duration: 0,
    genres: ['Drama', 'Thriller', 'Crime'],
    director: 'Biyi Bandele',
    cast: ['Ini Dima-Okojie', 'Nancy Isime', 'Kate Henshaw'],
    description: 'Two friends go on the run after a tragic accident at a wedding. A gripping Nigerian thriller series.',
    poster: 'https://images.unsplash.com/photo-1518331647614-7a1f04cd34cf?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1501426026826-31c667bdf23d?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Series',
    age_rating: 'R',
    cover: 'https://images.unsplash.com/photo-1501426026826-31c667bdf23d?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Biyi Bandele', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/45.jpg' },
      { name: 'Ini Dima-Okojie', role: 'Actress', character: 'Kemi', photo: 'https://randomuser.me/api/portraits/women/60.jpg' },
      { name: 'Nancy Isime', role: 'Actress', character: 'Sarah', photo: 'https://randomuser.me/api/portraits/women/35.jpg' },
      { name: 'Kate Henshaw', role: 'Actress', character: 'Lady Bridget', photo: 'https://randomuser.me/api/portraits/women/52.jpg' },
    ],
    release_date: '2022-05-05',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2022,
        episodes: [
          { id: 's1-1-1', episode_number: 1, title: 'The Wedding', duration: 45, description: 'A wedding turns deadly.' },
          { id: 's1-1-2', episode_number: 2, title: 'On the Run', duration: 48, description: 'The friends flee.' },
          { id: 's1-1-3', episode_number: 3, title: 'Secrets', duration: 46, description: 'Past secrets surface.' },
          { id: 's1-1-4', episode_number: 4, title: 'Reckoning', duration: 50, description: 'The truth comes out.' },
        ],
      },
    ],
  },
  {
    id: 's2',
    title: 'Far From Home',
    year: 2022,
    rating: 6.8,
    duration: 0,
    genres: ['Drama', 'Thriller'],
    director: 'C.J. Obasi',
    cast: ['Mike Afolarin', 'Adesua Etomi-Wellington', 'Richard Mofe-Damijo'],
    description: 'A young man from a poor background gets a scholarship to an elite school and uncovers dark secrets.',
    poster: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Series',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'C.J. Obasi', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/33.jpg' },
      { name: 'Mike Afolarin', role: 'Actor', character: 'Ishmael', photo: 'https://randomuser.me/api/portraits/men/22.jpg' },
      { name: 'Adesua Etomi-Wellington', role: 'Actress', character: 'Mrs. Alade', photo: 'https://randomuser.me/api/portraits/women/28.jpg' },
      { name: 'Richard Mofe-Damijo', role: 'Actor', character: 'The Principal', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
    ],
    release_date: '2022-12-16',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2022,
        episodes: [
          { id: 's2-1-1', episode_number: 1, title: 'The Scholarship', duration: 52, description: 'Ishmael wins a scholarship.' },
          { id: 's2-1-2', episode_number: 2, title: 'New World', duration: 50, description: 'Life at Wilmer Academy.' },
          { id: 's2-1-3', episode_number: 3, title: 'Secrets of the Elite', duration: 48, description: 'Dark truths emerge.' },
        ],
      },
    ],
  },
  {
    id: 's3',
    title: 'Anikulapo: Rise of the Spectre',
    year: 2024,
    rating: 6.9,
    duration: 0,
    genres: ['Drama', 'Fantasy', 'Romance'],
    director: 'Kunle Afolayan',
    cast: ['Kunle Remi', 'Bimbo Ademoye', 'Oyindamola Sanni'],
    description: 'The sequel to Anikulapo — Saro returns with the mystical bird and faces new battles in the Oyo Kingdom.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=1280&h=720&fit=crop',
    trending: false,
    featured: true,
    type: 'Series',
    age_rating: '16+',
    cover: 'https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Kunle Afolayan', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/40.jpg' },
      { name: 'Kunle Remi', role: 'Actor', character: 'Saro', photo: 'https://randomuser.me/api/portraits/men/58.jpg' },
      { name: 'Bimbo Ademoye', role: 'Actress', character: 'Arolake', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { name: 'Oyindamola Sanni', role: 'Actress', character: 'Asogba', photo: 'https://randomuser.me/api/portraits/women/62.jpg' },
    ],
    release_date: '2024-03-01',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2024,
        episodes: [
          { id: 's3-1-1', episode_number: 1, title: 'The Return', duration: 55, description: 'Saro returns with the bird.' },
          { id: 's3-1-2', episode_number: 2, title: 'New Enemies', duration: 53, description: 'Old foes resurface.' },
        ],
      },
    ],
  },
  {
    id: 's4',
    title: 'The Real Housewives of Lagos',
    year: 2022,
    rating: 5.8,
    duration: 0,
    genres: ['Reality', 'Drama', 'Comedy'],
    director: 'Various',
    cast: ['Carolyna Hutchings', 'Laura Ikeji', 'Mariam Timmer'],
    description: 'Reality series following the lives of wealthy women in Lagos. Drama, glamour, and friendship.',
    poster: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=1280&h=720&fit=crop',
    trending: false,
    featured: false,
    type: 'Series',
    age_rating: 'PG',
    cover: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Carolyna Hutchings', role: 'Actress', character: 'Herself', photo: 'https://randomuser.me/api/portraits/women/66.jpg' },
      { name: 'Laura Ikeji', role: 'Actress', character: 'Herself', photo: 'https://randomuser.me/api/portraits/women/71.jpg' },
      { name: 'Mariam Timmer', role: 'Actress', character: 'Herself', photo: 'https://randomuser.me/api/portraits/women/29.jpg' },
    ],
    release_date: '2022-04-08',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2022,
        episodes: [
          { id: 's4-1-1', episode_number: 1, title: 'Welcome to Lagos', duration: 42, description: 'Meet the housewives.' },
          { id: 's4-1-2', episode_number: 2, title: 'Drama Begins', duration: 44, description: 'Tensions rise.' },
        ],
      },
    ],
  },
  {
    id: 's5',
    title: 'Shaka Ilembe',
    year: 2023,
    rating: 7.5,
    duration: 0,
    genres: ['Drama', 'History', 'Biography'],
    director: 'Various',
    cast: ['Nomzamo Mbatha', 'Thembinkosi Mthembu', 'Lemogang Tsipa'],
    description: 'Epic drama about the rise of King Shaka Zulu. A landmark African historical series.',
    poster: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Series',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Nomzamo Mbatha', role: 'Actress', character: 'Nandi', photo: 'https://randomuser.me/api/portraits/women/50.jpg' },
      { name: 'Thembinkosi Mthembu', role: 'Actor', character: 'Shaka', photo: 'https://randomuser.me/api/portraits/men/63.jpg' },
      { name: 'Lemogang Tsipa', role: 'Actor', character: 'Dingiswayo', photo: 'https://randomuser.me/api/portraits/men/37.jpg' },
    ],
    release_date: '2023-06-18',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2023,
        episodes: [
          { id: 's5-1-1', episode_number: 1, title: 'The Birth', duration: 58, description: 'Young Shaka\'s origins.' },
          { id: 's5-1-2', episode_number: 2, title: 'Exile', duration: 56, description: 'Shaka in exile.' },
          { id: 's5-1-3', episode_number: 3, title: 'Return', duration: 57, description: 'Rise to power.' },
        ],
      },
    ],
  },
  {
    id: 's6',
    title: 'Shanty Town',
    year: 2023,
    rating: 7.2,
    duration: 0,
    genres: ['Crime', 'Thriller', 'Drama'],
    director: 'Charles Okpaleke',
    cast: ['Ini Edo', 'Chidi Mokeme', 'Nse Ikpe-Etim'],
    description: 'Women forced into prostitution find an unexpected way out when they stumble upon dangerous secrets. A raw Netflix Nigeria crime series.',
    poster: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Series',
    age_rating: '18+',
    cover: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Charles Okpaleke', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/22.jpg' },
      { name: 'Ini Edo', role: 'Actress', character: 'Alhaja', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { name: 'Chidi Mokeme', role: 'Actor', character: 'Scar', photo: 'https://randomuser.me/api/portraits/men/45.jpg' },
      { name: 'Nse Ikpe-Etim', role: 'Actress', character: 'Amaka', photo: 'https://randomuser.me/api/portraits/women/66.jpg' },
    ],
    release_date: '2023-01-27',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2023,
        episodes: [
          { id: 's6-1-1', episode_number: 1, title: 'The Trap', duration: 48, description: 'Women are lured into a dangerous world.' },
          { id: 's6-1-2', episode_number: 2, title: 'Survival', duration: 46, description: 'Alliances form under pressure.' },
          { id: 's6-1-3', episode_number: 3, title: 'The Heist', duration: 50, description: 'A plan for freedom takes shape.' },
          { id: 's6-1-4', episode_number: 4, title: 'Reckoning', duration: 52, description: 'Secrets are exposed.' },
          { id: 's6-1-5', episode_number: 5, title: 'Freedom', duration: 55, description: 'The final confrontation.' },
          { id: 's6-1-6', episode_number: 6, title: 'Aftermath', duration: 50, description: 'New beginnings emerge from chaos.' },
        ],
      },
    ],
  },
  {
    id: 's7',
    title: 'Castle & Castle',
    year: 2018,
    rating: 7.4,
    duration: 0,
    genres: ['Drama', 'Romance', 'Mystery'],
    director: 'Niji Akanni',
    cast: ['Richard Mofe-Damijo', 'Kate Henshaw', 'Dakore Akande'],
    description: 'A married power couple who are also legal partners navigate complex cases while keeping their marriage — and secrets — intact.',
    poster: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1280&h=720&fit=crop',
    trending: false,
    featured: true,
    type: 'Series',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Niji Akanni', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
      { name: 'Richard Mofe-Damijo', role: 'Actor', character: 'Tega Castle', photo: 'https://randomuser.me/api/portraits/men/63.jpg' },
      { name: 'Kate Henshaw', role: 'Actress', character: 'Ona Castle', photo: 'https://randomuser.me/api/portraits/women/52.jpg' },
      { name: 'Dakore Akande', role: 'Actress', character: 'Rita', photo: 'https://randomuser.me/api/portraits/women/29.jpg' },
    ],
    release_date: '2018-07-03',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2018,
        episodes: [
          { id: 's7-1-1', episode_number: 1, title: 'The Partnership', duration: 45, description: 'The Castle law firm takes on its first big case.' },
          { id: 's7-1-2', episode_number: 2, title: 'Conflict of Interest', duration: 43, description: 'Personal and professional worlds collide.' },
          { id: 's7-1-3', episode_number: 3, title: 'The Verdict', duration: 46, description: 'A shocking courtroom reveal.' },
        ],
      },
      {
        season_number: 2,
        title: 'Season 2',
        year: 2019,
        episodes: [
          { id: 's7-2-1', episode_number: 1, title: 'New Grounds', duration: 47, description: 'The Castles face their toughest case yet.' },
          { id: 's7-2-2', episode_number: 2, title: 'Betrayal', duration: 44, description: 'Trust is broken.' },
        ],
      },
    ],
  },
  {
    id: 's8',
    title: 'Breath of Life',
    year: 2023,
    rating: 6.6,
    duration: 0,
    genres: ['Drama', 'Romance', 'Family'],
    director: 'Damilola Orimogunje',
    cast: ['Jide Kene Achufusi', 'Bimbo Ademoye', 'Kunle Remi'],
    description: 'A medical drama set in a Lagos hospital where doctors, nurses, and patients face life-and-death situations entwined with love and loss.',
    poster: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1280&h=720&fit=crop',
    trending: false,
    featured: false,
    type: 'Series',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Damilola Orimogunje', role: 'Director', photo: 'https://randomuser.me/api/portraits/women/40.jpg' },
      { name: 'Jide Kene Achufusi', role: 'Actor', character: 'Dr. Obi', photo: 'https://randomuser.me/api/portraits/men/37.jpg' },
      { name: 'Bimbo Ademoye', role: 'Actress', character: 'Nurse Sola', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { name: 'Kunle Remi', role: 'Actor', character: 'Dr. Aaron', photo: 'https://randomuser.me/api/portraits/men/58.jpg' },
    ],
    release_date: '2023-09-15',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2023,
        episodes: [
          { id: 's8-1-1', episode_number: 1, title: 'First Shift', duration: 44, description: 'New doctors arrive at Lagos General.' },
          { id: 's8-1-2', episode_number: 2, title: 'Code Blue', duration: 43, description: 'A critical patient tests the team.' },
          { id: 's8-1-3', episode_number: 3, title: 'Complications', duration: 46, description: 'Personal feelings blur professional lines.' },
          { id: 's8-1-4', episode_number: 4, title: 'Recovery', duration: 45, description: 'Loss and healing shape the team.' },
        ],
      },
    ],
  },
  {
    id: 's9',
    title: 'Tinsel',
    year: 2008,
    rating: 6.5,
    duration: 0,
    genres: ['Drama', 'Romance', 'Comedy'],
    director: 'Various',
    cast: ['Ego Boyo', 'Iretiola Doyle', 'Wale Ojo'],
    description: 'Nigeria\'s longest-running soap opera set in the glamorous world of entertainment — love, betrayal, ambition, and fame behind the cameras.',
    poster: 'https://images.unsplash.com/photo-1493804714600-6edb1cd93080?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1280&h=720&fit=crop',
    trending: false,
    featured: false,
    type: 'Series',
    age_rating: 'PG',
    cover: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Ego Boyo', role: 'Actress', character: 'Brenda Mensah', photo: 'https://randomuser.me/api/portraits/women/35.jpg' },
      { name: 'Iretiola Doyle', role: 'Actress', character: 'Angela Dede', photo: 'https://randomuser.me/api/portraits/women/60.jpg' },
      { name: 'Wale Ojo', role: 'Actor', character: 'Soji Bankole', photo: 'https://randomuser.me/api/portraits/men/22.jpg' },
    ],
    release_date: '2008-11-03',
    pricing: { '480p': 1.99, '720p': 3.99, '1080p': 5.99, '4K': 9.99 },
    filmmakerId: 'filmmaker-2',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2008,
        episodes: [
          { id: 's9-1-1', episode_number: 1, title: 'Lights, Camera…', duration: 25, description: 'The entertainment world of Lagos unveiled.' },
          { id: 's9-1-2', episode_number: 2, title: 'Action!', duration: 25, description: 'Rivalries ignite on set.' },
          { id: 's9-1-3', episode_number: 3, title: 'Cut!', duration: 25, description: 'Behind-the-scenes drama unfolds.' },
        ],
      },
    ],
  },
  {
    id: 's10',
    title: 'Jemeji',
    year: 2018,
    rating: 6.8,
    duration: 0,
    genres: ['Drama', 'Mystery', 'Thriller'],
    director: 'Murphy Afolabi',
    cast: ['Femi Branch', 'Temitope Solaja', 'Fathia Williams'],
    description: 'Twins separated at birth are drawn back together by fate in a Yoruba community filled with tradition, rivalry, and dark family secrets.',
    poster: 'https://images.unsplash.com/photo-1493564738392-d148cfbd6eda?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1280&h=720&fit=crop',
    trending: false,
    featured: true,
    type: 'Series',
    age_rating: 'PG',
    cover: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Murphy Afolabi', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/33.jpg' },
      { name: 'Femi Branch', role: 'Actor', character: 'Baba Ibeji', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
      { name: 'Temitope Solaja', role: 'Actress', character: 'Adunni', photo: 'https://randomuser.me/api/portraits/women/28.jpg' },
      { name: 'Fathia Williams', role: 'Actress', character: 'Mama Ibeji', photo: 'https://randomuser.me/api/portraits/women/62.jpg' },
    ],
    release_date: '2018-09-10',
    pricing: { '480p': 1.99, '720p': 3.99, '1080p': 5.99, '4K': 9.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2018,
        episodes: [
          { id: 's10-1-1', episode_number: 1, title: 'Twins of Fate', duration: 35, description: 'A village learns of separated twins.' },
          { id: 's10-1-2', episode_number: 2, title: 'The Reunion', duration: 34, description: 'Two worlds collide.' },
          { id: 's10-1-3', episode_number: 3, title: 'Blood Ties', duration: 36, description: 'Family secrets begin to unravel.' },
        ],
      },
    ],
  },
  {
    id: 's11',
    title: 'MTV Shuga',
    year: 2009,
    rating: 6.7,
    duration: 0,
    genres: ['Drama', 'Romance'],
    director: 'Various',
    cast: ['Lupita Nyong\'o', 'Olumide Oworu', 'Eve D\'Souza'],
    description: 'A groundbreaking African series that tackles HIV/AIDS, sexual health, and social issues through the stories of young Africans navigating love and life.',
    poster: 'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1280&h=720&fit=crop',
    trending: false,
    featured: false,
    type: 'Series',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Giuliano Papadia', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/40.jpg' },
      { name: 'Lupita Nyong\'o', role: 'Actress', character: 'Ayira', photo: 'https://randomuser.me/api/portraits/women/50.jpg' },
      { name: 'Olumide Oworu', role: 'Actor', character: 'Tobi', photo: 'https://randomuser.me/api/portraits/men/22.jpg' },
    ],
    release_date: '2009-06-01',
    pricing: { '480p': 1.99, '720p': 3.99, '1080p': 5.99, '4K': 9.99 },
    filmmakerId: 'filmmaker-2',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2009,
        episodes: [
          { id: 's11-1-1', episode_number: 1, title: 'Choices', duration: 30, description: 'Young Nairobi friends face life-changing decisions.' },
          { id: 's11-1-2', episode_number: 2, title: 'Consequences', duration: 30, description: 'Actions have unexpected outcomes.' },
        ],
      },
    ],
  },
  {
    id: 's12',
    title: 'Nsolo',
    year: 2024,
    rating: 7.1,
    duration: 0,
    genres: ['Drama', 'Thriller', 'Crime'],
    director: 'Chuksie Ohazulume',
    cast: ['Stan Nze', 'Osas Ighodaro', 'Bimbo Ogunleye'],
    description: 'A detective series set in Abuja — Detective Nsolo investigates crimes that cut through the city\'s political elite, uncovering a vast conspiracy.',
    poster: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Series',
    age_rating: 'R',
    cover: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=1280&h=720&fit=crop',
    cast_crew: [
      { name: 'Chuksie Ohazulume', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/37.jpg' },
      { name: 'Stan Nze', role: 'Actor', character: 'Det. Nsolo', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
      { name: 'Osas Ighodaro', role: 'Actress', character: 'Prosecutor Ada', photo: 'https://randomuser.me/api/portraits/women/60.jpg' },
      { name: 'Bimbo Ogunleye', role: 'Actor', character: 'Chief Bankole', photo: 'https://randomuser.me/api/portraits/men/63.jpg' },
    ],
    release_date: '2024-02-14',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
    seasons: [
      {
        season_number: 1,
        title: 'Season 1',
        year: 2024,
        episodes: [
          { id: 's12-1-1', episode_number: 1, title: 'The Case', duration: 50, description: 'A senator\'s aide is found dead.' },
          { id: 's12-1-2', episode_number: 2, title: 'Deeper', duration: 48, description: 'The conspiracy widens.' },
          { id: 's12-1-3', episode_number: 3, title: 'Shadows', duration: 52, description: 'Nsolo is warned off the case.' },
          { id: 's12-1-4', episode_number: 4, title: 'The Leak', duration: 49, description: 'A source inside the government comes forward.' },
          { id: 's12-1-5', episode_number: 5, title: 'Endgame', duration: 55, description: 'The truth is finally exposed.' },
        ],
      },
    ],
  },
];